version: '3'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    fpm:
        build:
            context: ./php
        container_name: php
        volumes:
            - ./src:/var/www/html
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    db:
        image: mysql:latest
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: secret

    cache:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
          - redis-volume:/data

volumes:
  mysql-volume:
  redis-volume: